FROM python:3.8-slim

WORKDIR /app

# Copia o requirements.txt da raiz do projeto (..)
COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código da raiz para /app (..)
COPY ../ .

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

EXPOSE 5001

CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
