version: "3.9"

services:
  reserva:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5001
