version: '3.8'

services:
  api:
    build:
        context: .
        dockerfile: docker/dockerfile
    ports:
       - "5001:5001"
    volume:
       - .:/app
    entrypoint: 
      - FLASK_ENV=development
      - FLASK_APP=app.py
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5001

