version: "3.8"

services:
  reserva:
    build:
      context: ..               # Contexto é a raiz do projeto
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
